changelog:
  categories:
    - title: Breaking Changes ğŸ› 
      labels:
        - major
    - title: Exciting New Features ğŸ‰
      labels:
        - minor
    - title: Fix Bugs ğŸ›
      labels:
        - patch
    - title: Other Changes
      labels:
        - "*"